import { Product, Category, Review } from "@/types";

export const products: Product[] = [
  {
    id: "innessa-shampoo-001",
    name: "Botanical Repair Shampoo",
    category: "Shampoo",
    categorySlug: "shampoo",
    price: 899,
    originalPrice: 1199,
    discount: 25,
    stock: "In Stock",
    images: [
      "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600&q=80",
      "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600&q=80",
    ],
    description:
      "A luxurious botanical-infused shampoo that gently cleanses while restoring vitality to damaged hair. Enriched with rare plant extracts and proteins that penetrate deep into each strand.",
    ingredients: [
      "Aqua",
      "Sodium Lauryl Sulfate",
      "Argan Oil",
      "Keratin Protein",
      "Rosemary Extract",
      "Biotin",
      "Panthenol",
      "Vitamin E",
    ],
    benefits: [
      "Deep cleansing without stripping natural oils",
      "Repairs and strengthens hair shaft",
      "Adds brilliant shine and softness",
      "Reduces breakage by up to 70%",
    ],
    usage:
      "Apply to wet hair, lather gently, and rinse thoroughly. For best results, follow with Innessa Conditioner.",
    isFeatured: true,
    isBestSeller: true,
    rating: 4.8,
    reviews: 324,
    tags: ["repair", "botanical", "sulfate-free"],
  },
  {
    id: "innessa-mask-002",
    name: "Intensive Keratin Hair Mask",
    category: "Hair Mask",
    categorySlug: "hair-mask",
    price: 1299,
    originalPrice: 1599,
    discount: 19,
    stock: "In Stock",
    images: [
      "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600&q=80",
      "https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=600&q=80",
    ],
    description:
      "A deeply nourishing treatment mask formulated with medical-grade keratin and exotic oils. Transforms dry, brittle hair into silky, manageable tresses in just one use.",
    ingredients: [
      "Hydrolyzed Keratin",
      "Argan Oil",
      "Shea Butter",
      "Coconut Milk",
      "Hyaluronic Acid",
      "Vitamin B5",
      "Silk Amino Acids",
    ],
    benefits: [
      "Intense moisture restoration",
      "Eliminates frizz and flyaways",
      "Strengthens and smooths cuticle",
      "Visible results after first use",
    ],
    usage:
      "After shampooing, apply generously from mid-length to ends. Leave for 10-15 minutes, then rinse thoroughly.",
    isFeatured: true,
    isBestSeller: true,
    rating: 4.9,
    reviews: 512,
    tags: ["keratin", "intensive", "frizz-control"],
  },
  {
    id: "innessa-serum-003",
    name: "Gold Elixir Hair Serum",
    category: "Serum",
    categorySlug: "serum",
    price: 1499,
    originalPrice: 1999,
    discount: 25,
    stock: "In Stock",
    images: [
      "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&q=80",
      "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600&q=80",
    ],
    description:
      "A luxurious 24-karat gold-infused serum that creates an invisible shield around each strand, locking in moisture while delivering radiant shine. Our most coveted product.",
    ingredients: [
      "Cyclopentasiloxane",
      "24K Gold Particles",
      "Argan Oil",
      "Jojoba Oil",
      "Vitamin E",
      "Dimethicone",
      "Fragrance",
    ],
    benefits: [
      "Mirror-like shine and luminosity",
      "Heat protection up to 230°C",
      "Controls frizz for up to 72 hours",
      "Lightweight, non-greasy formula",
    ],
    usage:
      "Apply 2-3 drops to damp or dry hair, focusing on mid-lengths and ends. Do not rinse.",
    isFeatured: true,
    isNew: true,
    rating: 4.7,
    reviews: 198,
    tags: ["gold", "shine", "heat-protection"],
  },
  {
    id: "innessa-oil-004",
    name: "Ayurvedic Hair Growth Oil",
    category: "Oil",
    categorySlug: "oil",
    price: 799,
    originalPrice: 999,
    discount: 20,
    stock: "In Stock",
    images: [
      "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=600&q=80",
      "https://images.unsplash.com/photo-1607008829749-c0f284a49fc4?w=600&q=80",
    ],
    description:
      "A sacred blend of 12 Ayurvedic herbs cold-pressed with premium carrier oils. Stimulates dormant follicles, prevents hair fall, and promotes lustrous growth rooted in ancient wisdom.",
    ingredients: [
      "Cold-Pressed Coconut Oil",
      "Bhringraj Extract",
      "Amla Oil",
      "Brahmi",
      "Neem",
      "Castor Oil",
      "Fenugreek",
      "Curry Leaf Extract",
    ],
    benefits: [
      "Reduces hair fall by 80%",
      "Stimulates new hair growth",
      "Nourishes scalp and roots",
      "Prevents premature greying",
    ],
    usage:
      "Warm slightly and massage into scalp for 5-10 minutes. Leave overnight or for at least 2 hours before washing.",
    isBestSeller: true,
    rating: 4.8,
    reviews: 687,
    tags: ["ayurvedic", "growth", "scalp"],
  },
  {
    id: "innessa-conditioner-005",
    name: "Moisture Surge Conditioner",
    category: "Conditioner",
    categorySlug: "conditioner",
    price: 749,
    originalPrice: 999,
    discount: 25,
    stock: "In Stock",
    images: [
      "https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=600&q=80",
      "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600&q=80",
    ],
    description:
      "A rich, creamy conditioner that delivers 48-hour moisture retention. Formulated with marine collagen and tropical butter complex for hair that feels like silk.",
    ingredients: [
      "Marine Collagen",
      "Mango Butter",
      "Avocado Oil",
      "Cetyl Alcohol",
      "Glycerin",
      "Aloe Vera",
      "Green Tea Extract",
    ],
    benefits: [
      "48-hour moisture lock",
      "Detangles effortlessly",
      "Adds volume and body",
      "Color-safe formula",
    ],
    usage:
      "After shampooing, apply from roots to tips. Leave for 3-5 minutes and rinse with cool water.",
    isBestSeller: true,
    rating: 4.6,
    reviews: 289,
    tags: ["moisture", "detangling", "color-safe"],
  },
  {
    id: "innessa-spray-006",
    name: "Thermal Shield Hair Spray",
    category: "Hair Spray",
    categorySlug: "hair-spray",
    price: 649,
    originalPrice: 849,
    discount: 24,
    stock: "In Stock",
    images: [
      "https://images.unsplash.com/photo-1585751119414-ef2636f8aede?w=600&q=80",
      "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600&q=80",
    ],
    description:
      "A featherlight thermal spray that protects hair from heat damage while adding flexible hold. Infused with silk proteins that smooth the cuticle for a glossy finish.",
    ingredients: [
      "Aqua",
      "Silk Proteins",
      "PVP",
      "Panthenol",
      "Dimethicone",
      "Alcohol Denat",
      "Parfum",
    ],
    benefits: [
      "Heat protection up to 250°C",
      "Flexible, buildable hold",
      "Reduces humidity-induced frizz",
      "Adds brilliant shine",
    ],
    usage:
      "Spray evenly onto dry hair from 30cm distance. Style as desired. Reapply throughout the day if needed.",
    isNew: true,
    rating: 4.5,
    reviews: 143,
    tags: ["heat-protection", "hold", "shine"],
  },
  {
    id: "innessa-cream-007",
    name: "Velvet Leave-In Cream",
    category: "Leave-In Cream",
    categorySlug: "leave-in-cream",
    price: 949,
    originalPrice: 1249,
    discount: 24,
    stock: "In Stock",
    images: [
      "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600&q=80",
      "https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=600&q=80",
    ],
    description:
      "A sumptuous leave-in treatment that works around the clock to repair and protect. The ultra-light formula absorbs instantly, leaving hair velvety soft without any heaviness.",
    ingredients: [
      "Shea Butter",
      "Cetyl Alcohol",
      "Hydrolyzed Wheat Protein",
      "Argan Oil",
      "Glycerin",
      "Aloe Vera",
      "Vitamin E",
    ],
    benefits: [
      "All-day moisture and protection",
      "Reduces combing breakage",
      "Defines natural texture",
      "Weightless formula",
    ],
    usage:
      "Apply to damp or dry hair section by section. Do not rinse. Style as usual.",
    isFeatured: true,
    rating: 4.7,
    reviews: 221,
    tags: ["leave-in", "moisture", "repair"],
  },
  {
    id: "innessa-scalp-008",
    name: "Revive Scalp Treatment",
    category: "Scalp Treatment",
    categorySlug: "scalp-treatment",
    price: 1199,
    originalPrice: 1499,
    discount: 20,
    stock: "In Stock",
    images: [
      "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&q=80",
      "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=600&q=80",
    ],
    description:
      "A clinical-strength scalp serum that targets the root cause of hair concerns. Formulated with dermatologist-approved actives to balance the scalp microbiome and strengthen follicles.",
    ingredients: [
      "Salicylic Acid",
      "Niacinamide",
      "Zinc PCA",
      "Peppermint Oil",
      "Tea Tree Oil",
      "Biotin",
      "Caffeine",
    ],
    benefits: [
      "Reduces dandruff and flaking",
      "Balances scalp oil production",
      "Stimulates blood circulation",
      "Strengthens hair roots",
    ],
    usage:
      "Part hair and apply directly to scalp. Massage gently. Leave on without rinsing. Use 3 times per week.",
    isNew: true,
    rating: 4.9,
    reviews: 156,
    tags: ["scalp", "anti-dandruff", "clinical"],
  },
  {
    id: "innessa-kit-009",
    name: "Complete Hair Growth Kit",
    category: "Hair Growth Kit",
    categorySlug: "kits",
    price: 2999,
    originalPrice: 4499,
    discount: 33,
    stock: "In Stock",
    images: [
      "https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=600&q=80",
      "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600&q=80",
    ],
    description:
      "The ultimate hair transformation system. This curated kit includes our bestselling Growth Oil, Repair Shampoo, Scalp Treatment, and Keratin Mask — everything needed for visibly thicker, longer hair.",
    ingredients: [
      "Includes: Ayurvedic Growth Oil 100ml",
      "Botanical Repair Shampoo 200ml",
      "Revive Scalp Treatment 50ml",
      "Intensive Keratin Mask 200ml",
    ],
    benefits: [
      "Complete 30-day transformation program",
      "Reduces hair fall from week 1",
      "Visibly thicker hair in 30 days",
      "Save 33% vs buying individually",
    ],
    usage:
      "Follow the included 30-day program guide for maximum results.",
    isFeatured: true,
    isBestSeller: true,
    rating: 4.9,
    reviews: 432,
    tags: ["kit", "growth", "bestseller"],
  },
  {
    id: "innessa-travel-010",
    name: "Innessa Travel Essentials Kit",
    category: "Travel Kit",
    categorySlug: "kits",
    price: 1499,
    originalPrice: 1999,
    discount: 25,
    stock: "Coming Soon",
    images: [
      "https://images.unsplash.com/photo-1585751119414-ef2636f8aede?w=600&q=80",
      "https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=600&q=80",
    ],
    description:
      "Take your luxury hair care ritual anywhere. This chic TSA-approved travel set includes travel-sized versions of our hero products, beautifully packaged in a reusable pouch.",
    ingredients: [
      "Includes: Shampoo 50ml",
      "Conditioner 50ml",
      "Gold Elixir Serum 15ml",
      "Leave-In Cream 30ml",
      "Luxury Travel Pouch",
    ],
    benefits: [
      "TSA-approved sizes",
      "Premium travel pouch included",
      "Perfect gift set",
      "Full-size performance in mini format",
    ],
    usage: "Use as your regular Innessa routine, anywhere in the world.",
    isNew: true,
    rating: 4.6,
    reviews: 78,
    tags: ["travel", "gift", "mini"],
  },
];

export const categories: Category[] = [
  {
    id: "shampoo",
    name: "Shampoo",
    slug: "shampoo",
    description: "Gentle yet powerful cleansers for every hair type",
    image: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=400&q=80",
    count: 6,
  },
  {
    id: "hair-mask",
    name: "Hair Masks",
    slug: "hair-mask",
    description: "Deep conditioning treatments for transformative results",
    image: "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=400&q=80",
    count: 4,
  },
  {
    id: "serum",
    name: "Serums",
    slug: "serum",
    description: "Targeted treatments for shine, strength, and repair",
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&q=80",
    count: 5,
  },
  {
    id: "oil",
    name: "Hair Oils",
    slug: "oil",
    description: "Ancient wisdom meets modern luxury",
    image: "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=400&q=80",
    count: 8,
  },
  {
    id: "conditioner",
    name: "Conditioners",
    slug: "conditioner",
    description: "Silky formulas for effortless detangling",
    image: "https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=400&q=80",
    count: 5,
  },
  {
    id: "kits",
    name: "Gift Kits",
    slug: "kits",
    description: "Curated sets for complete hair transformation",
    image: "https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=400&q=80",
    count: 3,
  },
];

export const reviews: Review[] = [
  {
    id: "r1",
    name: "Priya Sharma",
    rating: 5,
    comment:
      "The Keratin Hair Mask completely transformed my frizzy hair. After years of struggle, I finally have the smooth, manageable hair I always dreamed of. Innessa is simply magical.",
    date: "March 2024",
    verified: true,
    avatar: "PS",
  },
  {
    id: "r2",
    name: "Ananya Krishnan",
    rating: 5,
    comment:
      "I have been using the Growth Kit for 6 weeks and the difference is incredible. My hair is noticeably thicker and the hair fall has reduced drastically. Worth every rupee!",
    date: "February 2024",
    verified: true,
    avatar: "AK",
  },
  {
    id: "r3",
    name: "Meera Patel",
    rating: 5,
    comment:
      "The Gold Elixir Serum is my holy grail product. My hair looks like I just stepped out of a salon every single day. The packaging is also so luxurious and beautiful.",
    date: "March 2024",
    verified: true,
    avatar: "MP",
  },
  {
    id: "r4",
    name: "Ritu Agarwal",
    rating: 4,
    comment:
      "Absolutely love the Ayurvedic Oil! The scent is heavenly and my scalp feels so healthy. My mother noticed my hair looking shinier and asked me for the brand name immediately.",
    date: "January 2024",
    verified: true,
    avatar: "RA",
  },
  {
    id: "r5",
    name: "Sneha Malhotra",
    rating: 5,
    comment:
      "Best shampoo I have ever used. My hair feels clean but not stripped. The botanical fragrance lingers beautifully all day. Switching to Innessa was the best decision for my hair.",
    date: "February 2024",
    verified: true,
    avatar: "SM",
  },
  {
    id: "r6",
    name: "Divya Nair",
    rating: 5,
    comment:
      "The Scalp Treatment fixed my dandruff issue in just two weeks when nothing else worked in years. I am genuinely amazed. The quality and effectiveness is truly world-class.",
    date: "March 2024",
    verified: true,
    avatar: "DN",
  },
];
